version: "3.4"
services:
  elasticsearch_8:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.15.0"
    environment:
      - bootstrap.memory_lock=${ES_MEMORY_LOCK:-false}
      - "ES_JAVA_OPTS=-Xms${TEST_ES_HEAP_SIZE:-500m} -Xmx${TEST_ES_HEAP_SIZE:-500m}"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "127.0.0.1:9250:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  elasticsearch_9:
    image: "docker.elastic.co/elasticsearch/elasticsearch:9.1.5"
    environment:
      - bootstrap.memory_lock=${ES_MEMORY_LOCK:-false}
      - "ES_JAVA_OPTS=-Xms${TEST_ES_HEAP_SIZE:-500m} -Xmx${TEST_ES_HEAP_SIZE:-500m}"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "127.0.0.1:9250:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
